Hello: I hate PHP and love JAVA

Home: Home

NewMatch: New Match

Welcome: Welcome

StatisticsOverview: Statistics Overview 

NeedImprovementonbackhand: Need Improvement on backhand! 

WLMatches: W L Matches 

PointsWon: Points Won 

PointsLost: Points Lost 

LastMatches: Last Matches 

MatchespointsStat: Matches points Stats 

GamesWonLost: Games Won/Lost 

GamesStats: Games Stats 

SetsWonLost: Sets Won/Lost 


Date: Date

Opponent: Opponent

Surface: Surface

Result: Result 

Details: Details

ViewDetails: View Details

ServiceStats: Service Stats 

Aces: Aces

Other: Other

FirstServeIn: First Serve In 

In: In

Out: Out

ServicePointsWonLost: Service Points Won/Lost 

ServicePoints: Service Points 

Lost: Lost

Won: Won

ReceivingPointsWonLost: Receiving Points Won/Lost

ReceivingPoints: Receiving Points 

Numberstats: Number stats

Totalservicepoints: Total service points 

WinnerStats: Winner Stats

Forehandwinners: Forehand winners

Backhandwinners: Backhand winners

Volleywinners: Volley winners

Overallwinners: Overall winners

Unforcederrorsstats: Unforced errors stats

Forehandunforcederrors: Forehand unforced errors

Backhandunforcederrors: Backhand unforced errors

Unforcederror: Unforced error

DoubleFaults: Double Faults

OverallUnforcedErrors: Overall Unforced Errors

VolleyUnforcedErrors: Volley Unforced Errors

ForehandUnforcedErrors: Forehand Unforced Errors

BackhandUnforcedErrors: Backhand Unforced Errors 

Tips: Tips

Acesgreat: Aces\: You have a great ace percentage. Well done!

Acesavarege: Aces\: You have an avarege ace percentage.

Acesbad: Aces\: You have a bad ace percentage. Need improvement!

Doublefaultslow: Double faults\: You have a low double fault percentage. Well done!

Doublefaultsavarege: Double faults\: You have an avarege double fault percentage.

Doublefaultshigh: Double faults\: You have a high double fault percentage. Need improvement!

Forehandwinnersgreat: Forehand winners\: You have a great forehand winner percentage. Well done!

Forehandwinnersavarege: Forehand winners\: You have an avarege forehand winner percentage.

Forehandwinnersbad: Forehand winners\: You have a bad forehand winner percentage. Need improvement!

Forehandunforcederrorslow: Forehand unforced errors\: You have a low forehand unforced error percentage. Well done!

Forehandunforcederrorsavarege: Forehand unforced errors\: You have an avarege forehand unforced error percentage.

Forehandunforcederrorshigh: Forehand unforced errors\: You have a high forehand unforced error percentage. Need improvement!

Backhandwinnersgreat: Backhand winners\: You have a great backhand winner percentage. Well done!

Backhandwinnersavarege: Backhand winners\: You have an avarege backhand winner percentage.

Backhandwinnersbad: Backhand winners\: You have a bad backhand winner percentage. Need improvement!

Backhandunforcederrorslow: Backhand unforced errors\: You have a low backhand unforced error percentage. Well done!

Backhandunforcederrorsavarege: Backhand unforced errors\: You have an avarege backhand unforced error percentage.

Backhandunforcederrorshigh: Backhand unforced errors\: You have a high backhand unforced error percentage. Need improvement!

Volleywinnersgreat: Volley winners\: You have a great volley winner percentage. Well done!

Volleywinnersavarege: Volley winners\: You have an avarege volley winner percentage.

Volleywinnersbad: Volley winners\: You have a bad volley winner percentage. Need improvement!

Volleyunforcederrorslow: Volley unforced errors\: You have a low volley unforced error percentage. Well done!

Voleyunforcederrorsavarege: Voley unforced errors\: You have an avarege volley unforced error percentage.

Voleyunforcederrorshigh: Voley unforced errors\: You have a high volley unforced error percentage. Need improvement!

