Hello: Eu odeio PHP e amo JAVA!

Home: Início

NewMatch: Nova Partida

Welcome: Bem-vindo

StatisticsOverview: Estatísticas Visão Geral

NeedImprovementonbackhand: Precisa melhorar o backhand! 

WLMatches: V D Partidas

PointsWon: Pontos ganhos

PointsLost: Pontos perdidos

LastMatches: Últimas partidas

MatchespointsStat: Estatísticas Pontos por partidas 

GamesWonLost: Jogos ganhos/perdidos

GamesStats: Estatísticas Jogos

SetsWonLost: Sets Ganhos/Perdidos

Date: Data

Opponent: Oponente

Surface: Superfície

Result: Resultado 

Details: Detalhes

ViewDetails: Ver Detalhes

ServiceStats: Estatísticas Saque

Aces: Aces

DoubleFaults: Faltas Duplas

Other: Outro

FirstServeIn: Saques certos de primeira

In: Dentro

Out: Fora

ServicePointsWonLost: Pontos de Saque Ganhos/Perdidos

ServicePoints: Pontos de Saque

Lost: Perdidos

Won: Ganhos

ReceivingPointsWonLost: Pontos Recepção Ganhos/Perdidos

ReceivingPoints: Pontos Recepção

Numberstats: Estatísticas Números

Totalservicepoints: Total Pontos de Saque

WinnerStats: Estatísticas Vencedor

Forehandwinners: Forehand Vencedor

Backhandwinners: Backhand Vencedor

Volleywinners: Volley Vencedor

Overallwinners: Vencedor Geral

Unforcederrorsstats: Estatísticas Erros não forçados

Forehandunforcederrors: Forehand Erros não forçados

Backhandunforcederrors: Backhand Erros não forçados

Unforcederror: Erros não forçados



OverallUnforcedErrors: Erros não forçados Geral

VolleyUnforcedErrors: Volley Erros não forçados

ForehandUnforcedErrors: Forehand Erros não forçados

BackhandUnforcedErrors: Backhand Erros não forçados

Tips: Dicas

Acesgreat: Aces\: Você tem uma boa porcentagem. Bom trabalho!

Acesavarege: Aces\: Você tem uma  porcentagem média.

Acesbad: Aces\: Você tem uma  porcentagem ruim. Precisa melhorar!

Doublefaultslow: Faltas duplas\:  Você tem uma baixa porcentagem de faltas duplas. Bom trabalho!

Doublefaultsavarege: Faltas duplas\: Você tem uma  porcentagem média de faltas duplas.

Doublefaultshigh: Faltas duplas\: Você tem uma  alta porcentagem de faltas duplas. Precisa melhorar!

Forehandwinnersgreat: Forehand Vencedor\: Você tem uma boa porcentagem de Vencedor Forehand. Bom trabalho!

Forehandwinnersavarege: Forehand Vencedor\: Você tem uma porcentagem média de Vencedor Forehand.

Forehandwinnersbad: Forehand Vencedor\: Você tem uma baixa porcentagem de Vencedor Forehand. Precisa melhorar!

Forehandunforcederrorslow: Forehand Erros não forçados\: Você tem uma baixa porcentagem de Erros não forçados no Forehand. Bom trabalho!

Forehandunforcederrorsavarege: Forehand Erros não forçados\: Você tem uma  porcentagem média de Erros não forçados no Forehand.

Forehandunforcederrorshigh: Forehand Erros não forçados\: Você tem uma alta porcentagem de Erros não forçados no Forehand. Precisa melhorar!

Backhandwinnersgreat: Backhand Vencedor\: Você tem uma boa porcentagem  de Vencedor backhand. Bom trabalho!

Backhandwinnersavarege: Backhand Vencedor\: Você tem uma  porcentagem média de Vencedor backhand.

Backhandwinnersbad: Backhand Vencedor\: Você tem uma porcentagem ruim de Vencedor no Backhand. Precisa melhorar!

Backhandunforcederrorslow: Backhand erros não forçados\: Você tem uma baixa porcentagem de erros não forçados no backhand. Bom trabalho!

Backhandunforcederrorsavarege: Backhand erros não forçados\: Você tem uma  porcentagem média de Erros não forçados no backhand.

Backhandunforcederrorshigh: Backhand erros não forçados\: Você tem uma alta porcentagem de Erros não forçados no Forehand. Precisa melhorar!

Volleywinnersgreat: Volley Vencedor\: Você tem uma boa porcentagem de Vencedor Volley. Bom trabalho!

Volleywinnersavarege: Volley Vencedor\: Você tem uma porcentagem média de Vencedor Volley.

Volleywinnersbad: Volley Vencedor\: Você tem uma porcentagem ruim de venceodr Volley. Precisa melhorar!

Volleyunforcederrorslow: Volley erros não forçados\: Você tem uma baixa porcentagem de erros não forçado no Volley. Bom trabalho!

Voleyunforcederrorsavarege: Voley erros não forçados\: Você tem uma porcentagem média de erros não forçados.

Voleyunforcederrorshigh: Voley erros não forçados\: Você tem uma alta porcentagem de erros não forçados no Volley. Precisa melhorar!

